# Generated by Django 4.0.4 on 2022-05-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('fecha_atencion', models.DateTimeField(verbose_name='Fecha Atencion')),
            ],
            options={
                'verbose_name_plural': 'paciente',
                'db_table': 'paciente',
                'ordering': ('id',),
            },
        ),
    ]
