# Generated by Django 4.0.4 on 2022-05-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_atencion',
            field=models.DateTimeField(verbose_name='Fecha Atencion'),
        ),
    ]
