# Generated by Django 4.0.4 on 2022-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_pacientes_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_atencion',
            field=models.DateField(verbose_name='Fecha Atencion'),
        ),
    ]
